source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!
project 'Train'

target 'Train' do

pod 'AFNetworking', '~> 3.1.0'
pod 'CorePlot', '~> 2.1'
pod 'JSONModel', '~> 1.3.0'
pod 'MJRefresh', '~> 3.1.12'

end
